// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: control.proto

package controlv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Envelope is the control-stream unit. Identity in Hello is informational;
// the gateway must take user_id/client_id from the mTLS certificate only.
type Envelope struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Seq   uint64                 `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*Envelope_Hello
	//	*Envelope_HelloAck
	//	*Envelope_OpenTunnel
	//	*Envelope_OpenTunnelAck
	//	*Envelope_CloseTunnel
	//	*Envelope_CloseTunnelAck
	//	*Envelope_KeepAlive
	//	*Envelope_Error
	Payload       isEnvelope_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Envelope) Reset() {
	*x = Envelope{}
	mi := &file_control_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Envelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Envelope) ProtoMessage() {}

func (x *Envelope) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Envelope.ProtoReflect.Descriptor instead.
func (*Envelope) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{0}
}

func (x *Envelope) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *Envelope) GetPayload() isEnvelope_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Envelope) GetHello() *Hello {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_Hello); ok {
			return x.Hello
		}
	}
	return nil
}

func (x *Envelope) GetHelloAck() *HelloAck {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_HelloAck); ok {
			return x.HelloAck
		}
	}
	return nil
}

func (x *Envelope) GetOpenTunnel() *OpenTunnel {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_OpenTunnel); ok {
			return x.OpenTunnel
		}
	}
	return nil
}

func (x *Envelope) GetOpenTunnelAck() *OpenTunnelAck {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_OpenTunnelAck); ok {
			return x.OpenTunnelAck
		}
	}
	return nil
}

func (x *Envelope) GetCloseTunnel() *CloseTunnel {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_CloseTunnel); ok {
			return x.CloseTunnel
		}
	}
	return nil
}

func (x *Envelope) GetCloseTunnelAck() *CloseTunnelAck {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_CloseTunnelAck); ok {
			return x.CloseTunnelAck
		}
	}
	return nil
}

func (x *Envelope) GetKeepAlive() *KeepAlive {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_KeepAlive); ok {
			return x.KeepAlive
		}
	}
	return nil
}

func (x *Envelope) GetError() *Error {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isEnvelope_Payload interface {
	isEnvelope_Payload()
}

type Envelope_Hello struct {
	Hello *Hello `protobuf:"bytes,10,opt,name=hello,proto3,oneof"`
}

type Envelope_HelloAck struct {
	HelloAck *HelloAck `protobuf:"bytes,11,opt,name=hello_ack,json=helloAck,proto3,oneof"`
}

type Envelope_OpenTunnel struct {
	OpenTunnel *OpenTunnel `protobuf:"bytes,12,opt,name=open_tunnel,json=openTunnel,proto3,oneof"`
}

type Envelope_OpenTunnelAck struct {
	OpenTunnelAck *OpenTunnelAck `protobuf:"bytes,13,opt,name=open_tunnel_ack,json=openTunnelAck,proto3,oneof"`
}

type Envelope_CloseTunnel struct {
	CloseTunnel *CloseTunnel `protobuf:"bytes,14,opt,name=close_tunnel,json=closeTunnel,proto3,oneof"`
}

type Envelope_CloseTunnelAck struct {
	CloseTunnelAck *CloseTunnelAck `protobuf:"bytes,15,opt,name=close_tunnel_ack,json=closeTunnelAck,proto3,oneof"`
}

type Envelope_KeepAlive struct {
	KeepAlive *KeepAlive `protobuf:"bytes,16,opt,name=keep_alive,json=keepAlive,proto3,oneof"`
}

type Envelope_Error struct {
	Error *Error `protobuf:"bytes,17,opt,name=error,proto3,oneof"`
}

func (*Envelope_Hello) isEnvelope_Payload() {}

func (*Envelope_HelloAck) isEnvelope_Payload() {}

func (*Envelope_OpenTunnel) isEnvelope_Payload() {}

func (*Envelope_OpenTunnelAck) isEnvelope_Payload() {}

func (*Envelope_CloseTunnel) isEnvelope_Payload() {}

func (*Envelope_CloseTunnelAck) isEnvelope_Payload() {}

func (*Envelope_KeepAlive) isEnvelope_Payload() {}

func (*Envelope_Error) isEnvelope_Payload() {}

type Hello struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProtocolMin   uint32                 `protobuf:"varint,1,opt,name=protocol_min,json=protocolMin,proto3" json:"protocol_min,omitempty"`
	ProtocolMax   uint32                 `protobuf:"varint,2,opt,name=protocol_max,json=protocolMax,proto3" json:"protocol_max,omitempty"`
	ClientVersion string                 `protobuf:"bytes,3,opt,name=client_version,json=clientVersion,proto3" json:"client_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Hello) Reset() {
	*x = Hello{}
	mi := &file_control_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hello) ProtoMessage() {}

func (x *Hello) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hello.ProtoReflect.Descriptor instead.
func (*Hello) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{1}
}

func (x *Hello) GetProtocolMin() uint32 {
	if x != nil {
		return x.ProtocolMin
	}
	return 0
}

func (x *Hello) GetProtocolMax() uint32 {
	if x != nil {
		return x.ProtocolMax
	}
	return 0
}

func (x *Hello) GetClientVersion() string {
	if x != nil {
		return x.ClientVersion
	}
	return ""
}

type HelloAck struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Protocol       uint32                 `protobuf:"varint,1,opt,name=protocol,proto3" json:"protocol,omitempty"`
	GatewayVersion string                 `protobuf:"bytes,2,opt,name=gateway_version,json=gatewayVersion,proto3" json:"gateway_version,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *HelloAck) Reset() {
	*x = HelloAck{}
	mi := &file_control_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloAck) ProtoMessage() {}

func (x *HelloAck) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloAck.ProtoReflect.Descriptor instead.
func (*HelloAck) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{2}
}

func (x *HelloAck) GetProtocol() uint32 {
	if x != nil {
		return x.Protocol
	}
	return 0
}

func (x *HelloAck) GetGatewayVersion() string {
	if x != nil {
		return x.GatewayVersion
	}
	return ""
}

type OpenTunnel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subdomain     string                 `protobuf:"bytes,1,opt,name=subdomain,proto3" json:"subdomain,omitempty"` // optional request; gateway authorizes
	Persist       bool                   `protobuf:"varint,2,opt,name=persist,proto3" json:"persist,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenTunnel) Reset() {
	*x = OpenTunnel{}
	mi := &file_control_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenTunnel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenTunnel) ProtoMessage() {}

func (x *OpenTunnel) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenTunnel.ProtoReflect.Descriptor instead.
func (*OpenTunnel) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{3}
}

func (x *OpenTunnel) GetSubdomain() string {
	if x != nil {
		return x.Subdomain
	}
	return ""
}

func (x *OpenTunnel) GetPersist() bool {
	if x != nil {
		return x.Persist
	}
	return false
}

type OpenTunnelAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TunnelId      string                 `protobuf:"bytes,1,opt,name=tunnel_id,json=tunnelId,proto3" json:"tunnel_id,omitempty"`
	Hostname      string                 `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	PublicUrl     string                 `protobuf:"bytes,3,opt,name=public_url,json=publicUrl,proto3" json:"public_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenTunnelAck) Reset() {
	*x = OpenTunnelAck{}
	mi := &file_control_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenTunnelAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenTunnelAck) ProtoMessage() {}

func (x *OpenTunnelAck) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenTunnelAck.ProtoReflect.Descriptor instead.
func (*OpenTunnelAck) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{4}
}

func (x *OpenTunnelAck) GetTunnelId() string {
	if x != nil {
		return x.TunnelId
	}
	return ""
}

func (x *OpenTunnelAck) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *OpenTunnelAck) GetPublicUrl() string {
	if x != nil {
		return x.PublicUrl
	}
	return ""
}

type CloseTunnel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TunnelId      string                 `protobuf:"bytes,1,opt,name=tunnel_id,json=tunnelId,proto3" json:"tunnel_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseTunnel) Reset() {
	*x = CloseTunnel{}
	mi := &file_control_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseTunnel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseTunnel) ProtoMessage() {}

func (x *CloseTunnel) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseTunnel.ProtoReflect.Descriptor instead.
func (*CloseTunnel) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{5}
}

func (x *CloseTunnel) GetTunnelId() string {
	if x != nil {
		return x.TunnelId
	}
	return ""
}

type CloseTunnelAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TunnelId      string                 `protobuf:"bytes,1,opt,name=tunnel_id,json=tunnelId,proto3" json:"tunnel_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseTunnelAck) Reset() {
	*x = CloseTunnelAck{}
	mi := &file_control_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseTunnelAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseTunnelAck) ProtoMessage() {}

func (x *CloseTunnelAck) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseTunnelAck.ProtoReflect.Descriptor instead.
func (*CloseTunnelAck) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{6}
}

func (x *CloseTunnelAck) GetTunnelId() string {
	if x != nil {
		return x.TunnelId
	}
	return ""
}

type KeepAlive struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UnixMs        int64                  `protobuf:"varint,1,opt,name=unix_ms,json=unixMs,proto3" json:"unix_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeepAlive) Reset() {
	*x = KeepAlive{}
	mi := &file_control_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeepAlive) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeepAlive) ProtoMessage() {}

func (x *KeepAlive) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeepAlive.ProtoReflect.Descriptor instead.
func (*KeepAlive) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{7}
}

func (x *KeepAlive) GetUnixMs() int64 {
	if x != nil {
		return x.UnixMs
	}
	return 0
}

type Error struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	TunnelId      string                 `protobuf:"bytes,3,opt,name=tunnel_id,json=tunnelId,proto3" json:"tunnel_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_control_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{8}
}

func (x *Error) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Error) GetTunnelId() string {
	if x != nil {
		return x.TunnelId
	}
	return ""
}

// DataPreamble is written at the start of each data stream before HTTP/1.1.
type DataPreamble struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TunnelId      string                 `protobuf:"bytes,1,opt,name=tunnel_id,json=tunnelId,proto3" json:"tunnel_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataPreamble) Reset() {
	*x = DataPreamble{}
	mi := &file_control_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataPreamble) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataPreamble) ProtoMessage() {}

func (x *DataPreamble) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataPreamble.ProtoReflect.Descriptor instead.
func (*DataPreamble) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{9}
}

func (x *DataPreamble) GetTunnelId() string {
	if x != nil {
		return x.TunnelId
	}
	return ""
}

var File_control_proto protoreflect.FileDescriptor

const file_control_proto_rawDesc = "" +
	"\n" +
	"\rcontrol.proto\x12\rpasserelle.v1\"\x88\x04\n" +
	"\bEnvelope\x12\x10\n" +
	"\x03seq\x18\x01 \x01(\x04R\x03seq\x12,\n" +
	"\x05hello\x18\n" +
	" \x01(\v2\x14.passerelle.v1.HelloH\x00R\x05hello\x126\n" +
	"\thello_ack\x18\v \x01(\v2\x17.passerelle.v1.HelloAckH\x00R\bhelloAck\x12<\n" +
	"\vopen_tunnel\x18\f \x01(\v2\x19.passerelle.v1.OpenTunnelH\x00R\n" +
	"openTunnel\x12F\n" +
	"\x0fopen_tunnel_ack\x18\r \x01(\v2\x1c.passerelle.v1.OpenTunnelAckH\x00R\ropenTunnelAck\x12?\n" +
	"\fclose_tunnel\x18\x0e \x01(\v2\x1a.passerelle.v1.CloseTunnelH\x00R\vcloseTunnel\x12I\n" +
	"\x10close_tunnel_ack\x18\x0f \x01(\v2\x1d.passerelle.v1.CloseTunnelAckH\x00R\x0ecloseTunnelAck\x129\n" +
	"\n" +
	"keep_alive\x18\x10 \x01(\v2\x18.passerelle.v1.KeepAliveH\x00R\tkeepAlive\x12,\n" +
	"\x05error\x18\x11 \x01(\v2\x14.passerelle.v1.ErrorH\x00R\x05errorB\t\n" +
	"\apayload\"t\n" +
	"\x05Hello\x12!\n" +
	"\fprotocol_min\x18\x01 \x01(\rR\vprotocolMin\x12!\n" +
	"\fprotocol_max\x18\x02 \x01(\rR\vprotocolMax\x12%\n" +
	"\x0eclient_version\x18\x03 \x01(\tR\rclientVersion\"O\n" +
	"\bHelloAck\x12\x1a\n" +
	"\bprotocol\x18\x01 \x01(\rR\bprotocol\x12'\n" +
	"\x0fgateway_version\x18\x02 \x01(\tR\x0egatewayVersion\"D\n" +
	"\n" +
	"OpenTunnel\x12\x1c\n" +
	"\tsubdomain\x18\x01 \x01(\tR\tsubdomain\x12\x18\n" +
	"\apersist\x18\x02 \x01(\bR\apersist\"g\n" +
	"\rOpenTunnelAck\x12\x1b\n" +
	"\ttunnel_id\x18\x01 \x01(\tR\btunnelId\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x12\x1d\n" +
	"\n" +
	"public_url\x18\x03 \x01(\tR\tpublicUrl\"*\n" +
	"\vCloseTunnel\x12\x1b\n" +
	"\ttunnel_id\x18\x01 \x01(\tR\btunnelId\"-\n" +
	"\x0eCloseTunnelAck\x12\x1b\n" +
	"\ttunnel_id\x18\x01 \x01(\tR\btunnelId\"$\n" +
	"\tKeepAlive\x12\x17\n" +
	"\aunix_ms\x18\x01 \x01(\x03R\x06unixMs\"R\n" +
	"\x05Error\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1b\n" +
	"\ttunnel_id\x18\x03 \x01(\tR\btunnelId\"+\n" +
	"\fDataPreamble\x12\x1b\n" +
	"\ttunnel_id\x18\x01 \x01(\tR\btunnelIdB3Z1github.com/gauthier/passerelle/protocol/controlv1b\x06proto3"

var (
	file_control_proto_rawDescOnce sync.Once
	file_control_proto_rawDescData []byte
)

func file_control_proto_rawDescGZIP() []byte {
	file_control_proto_rawDescOnce.Do(func() {
		file_control_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_control_proto_rawDesc), len(file_control_proto_rawDesc)))
	})
	return file_control_proto_rawDescData
}

var file_control_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_control_proto_goTypes = []any{
	(*Envelope)(nil),       // 0: passerelle.v1.Envelope
	(*Hello)(nil),          // 1: passerelle.v1.Hello
	(*HelloAck)(nil),       // 2: passerelle.v1.HelloAck
	(*OpenTunnel)(nil),     // 3: passerelle.v1.OpenTunnel
	(*OpenTunnelAck)(nil),  // 4: passerelle.v1.OpenTunnelAck
	(*CloseTunnel)(nil),    // 5: passerelle.v1.CloseTunnel
	(*CloseTunnelAck)(nil), // 6: passerelle.v1.CloseTunnelAck
	(*KeepAlive)(nil),      // 7: passerelle.v1.KeepAlive
	(*Error)(nil),          // 8: passerelle.v1.Error
	(*DataPreamble)(nil),   // 9: passerelle.v1.DataPreamble
}
var file_control_proto_depIdxs = []int32{
	1, // 0: passerelle.v1.Envelope.hello:type_name -> passerelle.v1.Hello
	2, // 1: passerelle.v1.Envelope.hello_ack:type_name -> passerelle.v1.HelloAck
	3, // 2: passerelle.v1.Envelope.open_tunnel:type_name -> passerelle.v1.OpenTunnel
	4, // 3: passerelle.v1.Envelope.open_tunnel_ack:type_name -> passerelle.v1.OpenTunnelAck
	5, // 4: passerelle.v1.Envelope.close_tunnel:type_name -> passerelle.v1.CloseTunnel
	6, // 5: passerelle.v1.Envelope.close_tunnel_ack:type_name -> passerelle.v1.CloseTunnelAck
	7, // 6: passerelle.v1.Envelope.keep_alive:type_name -> passerelle.v1.KeepAlive
	8, // 7: passerelle.v1.Envelope.error:type_name -> passerelle.v1.Error
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_control_proto_init() }
func file_control_proto_init() {
	if File_control_proto != nil {
		return
	}
	file_control_proto_msgTypes[0].OneofWrappers = []any{
		(*Envelope_Hello)(nil),
		(*Envelope_HelloAck)(nil),
		(*Envelope_OpenTunnel)(nil),
		(*Envelope_OpenTunnelAck)(nil),
		(*Envelope_CloseTunnel)(nil),
		(*Envelope_CloseTunnelAck)(nil),
		(*Envelope_KeepAlive)(nil),
		(*Envelope_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_control_proto_rawDesc), len(file_control_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_control_proto_goTypes,
		DependencyIndexes: file_control_proto_depIdxs,
		MessageInfos:      file_control_proto_msgTypes,
	}.Build()
	File_control_proto = out.File
	file_control_proto_goTypes = nil
	file_control_proto_depIdxs = nil
}
